kind: pipeline
name: matrix-bot

steps:
- name: docker  
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: docker-registry.dyonb.nl/dyon/matrix-bot
    auto_tag: true
    registry: docker-registry.dyonb.nl
    dockerfile: Dockerfile